export const productForm = [
  {
    key: "title",
    value: "title",
    label: "Products",
    placeholder: "Enter product name",
    type: "default",
    required: true,
    message: "Enter product name",
    default_value: "",
    displayLength: 400,
  },
  {
    key: "price",
    value: "price",
    label: "Buying price",
    placeholder: "Enter buying price",
    type: "number",
    required: true,
    message: "Enter buying price",
    default_value: "",
    displayLength: 300,
  },
  {
    key: "quantity",
    value: "quantity",
    label: "Quantity",
    placeholder: "Enter product quantity",
    type: "number",
    required: true,
    message: "Enter product quantity",
    default_value: "",
    displayLength: 300,
  },
  {
    key: "threshold",
    value: "threshold",
    label: "Threshold Value",
    placeholder: "Enter threshold value",
    type: "number",
    required: true,
    message: "Enter threshold value",
    default_value: "",
    displayLength: 300,
  },
  {
    key: "expiryDate",
    value: "expiryDate",
    label: "Expiry Date",
    placeholder: "Enter expiry date",
    type: "datetime",
    required: true,
    message: "Enter expiry date",
    default_value: "",
    displayLength: 300,
  },
];
